import Speak = require("sitecore/shell/client/Speak/Assets/lib/core/1.2/SitecoreSpeak");

class MetroHint extends Speak.ControlBase {
  // #region Public Properties
  // This region was generated by a tool. Changes to this region may cause incorrect behavior and will be lost if the code is regenerated.
  public Hint: string;
  public IsVisible: boolean;
  public Text: string;
  public Tooltip: string;
  // #endregion
}

Sitecore.component(["metro"], MetroHint, "MetroHint");
