import Speak = require("sitecore/shell/client/Speak/Assets/lib/core/1.2/SitecoreSpeak");

class MetroRating extends Speak.ControlBase {
  // #region Public Properties
  // This region was generated by a tool. Changes to this region may cause incorrect behavior and will be lost if the code is regenerated.
  public IsVisible: boolean;
  public Score: number;
  public ShowScore: boolean;
  public Stars: number;
  public Text: string;
  public Tooltip: string;
  // #endregion

  private control: any;

  initialized() {
    this.control = (<any>$(this.el)).rating({
      score: this.Score,
      stars: this.Stars,
      showScore: this.ShowScore,
      scoreHint: this.Text,
      click: (value, rating) => this.clicked(value, rating)
    });

    this.on("change:Score", this.update, this);
  }

  private update() {
    this.control.rating("rate", this.Score);
  }

  private clicked(value, rating) {
    this.Score = value;
  }
}

Sitecore.component(["metro"], MetroRating, "MetroRating");
