import Speak = require("sitecore/shell/client/Speak/Assets/lib/core/1.2/SitecoreSpeak");

class MetroShortcut extends Speak.ControlBase {
  // #region Public Properties
  // This region was generated by a tool. Changes to this region may cause incorrect behavior and will be lost if the code is regenerated.
  public IsEnabled: boolean;
  public IsVisible: boolean;
  public SmallText: string;
  public Text: string;
  public Tooltip: string;
  public Type: string;
  // #endregion

  click() {
    var click = $(this.el).data("sc-click");
    if (click) {
      Sitecore.Speak.Events.handleEvent(click, this);
    }
  }              
}

Sitecore.Speak.component(MetroShortcut, "MetroShortcut");
