import Speak = require("sitecore/shell/client/Speak/Assets/lib/core/1.2/SitecoreSpeak");

class MetroProgressBar extends Speak.ControlBase {
  // #region Public Properties
  // This region was generated by a tool. Changes to this region may cause incorrect behavior and will be lost if the code is regenerated.
  public IsVisible: boolean;
  public Tooltip: string;
  public Foreground: string;
  public Value: number;
  // #endregion

  private control: any

  initialized(): void {
    this.control = (<any>$(this.el)).progressbar({
      value: this.Value,
      color: "bg-" + this.Foreground,
      onchange: (value) => this.changed(value)
    });

    this.on("change:Value", this.update, this);
  }

  private update(value): void {
    this.control.progressbar("value", this.Value);
  }

  private changed(value): void {
    this.Value = value;
  }
}

Sitecore.component(["metro"], MetroProgressBar, "MetroProgressBar");
